### ISSUE TITLE
Latest scalarizr no longer recognizes it's in cloudstack

### ISSUE THREAD

**Issue by awheeler** [Scalr/scalarizr#12]
The file /etc/scalr/public.d/config.ini now sets general.platform = ec2 rather than cloudstack, even though it's running in cloudstack, and scalarizr-cloudstack is installed.
I've been using that value to easily determine which platform I am on, and now it is incorrect.

**Comment by awheeler** [comment]
This is as of the 3.2 stable change.  Happens in 3.2.1 and 3.2.2

**Comment by maratkomarov** [comment]
Try to use the same file from private.d

**Comment by awheeler** [comment]
That fixed it, thank you.
