### ISSUE TITLE
Possible leak in scalr-upd-client

### ISSUE THREAD

**Issue by awheeler** [Scalr/scalarizr#9]
Running CentOS 6.5 in CloudStack.
Python 2.6.6
Scalarizr-base 2.12.6-1

Over time, the scalr-upd-client daemon grows until it gets killed by the OOM killer (I've seeing > 1GB).

**Comment by maratkomarov** [comment]
Could you please test Scalarizr 3.1.27 from http://repo.scalr.net/rpm/latest/rhel/ ?
It is running python 2.7.x and shouldn't have such problem.

**Comment by awheeler** [comment]
Will do.  Is this a known issue?  I'll still be running python 2.6.6.

**Comment by maratkomarov** [comment]
We've experienced several times leaks with 2.6, so this could be the cause.
The new 3.1.x package uses it's own embedded Python 2.7 and doesn't depend from system python.

**Comment by awheeler** [comment]
It looks like the 3.1.x package does fix this, but I don't really want to move away from using the stable branch (I've had some issues in the past with using latest, though I don't recall now exactly what they were).
I see that the 2.x series is hard-coded to use python2.6, so even if I get 2.7 installed, I can't use it cleanly.
When do you foresee the embedded python making it into stable?  And what about changing stable to use just python, rather than python2.6 so I can use a locally installed python 2.7?
So for now, I am restarting the 2.x series scalr-upd-client daily in a cronjob.

**Comment by maratkomarov** [comment]
New stable with embedded Python will be available in February. As for using non-system python for stable release: it's not easy to do - there are a lot of requirements (~20) that you also need to install, and some of them are not pyre python modules.

**Comment by awheeler** [comment]
Confirmed fixed with the new stable.  Thank yo.
